# Used for traffic analysis and security auditing
log-queries

# Do not use the system's built-in resolv.conf file
no-resolv

# Strictly use upstream servers in order
strict-order

# Custom Domain Name Resolution
address=/ollama.local/134.84.61.26
address=/ollama.local/::1
ptr-record=26.61.84.134.in-addr.arpa, ollama.local
