server:
  port: 8989

spring:
  profiles:
    active: dev

agenthub:
  jwt:
    admin-secret-key: agent_jwt_secret_key_for_admin_access_256_bits_required
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: agent_jwt_secret_key_for_user_access_256_bits_required
    user-ttl: 7200000
    user-token-name: authorization

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
